package test;

public enum TipoEvento {
	GRUPO_CHEGA_EM, GRUPO_CHEGOU, GRUPO_TERMINA_PEDIR_EM,
	PEDIDO_ADICIONADO_FILAPED, PEDIDO_SAIU_FILA, 
	COZINHA_PREPARANDO_PEDIDO, COZINHA_TERMINA_PEDIDO_EM, COZINHA_TERMINOU_PEDIDO,
	GRUPO_ADICIONADO_FILABALC, GRUPO_ADICIONADO_FILAMESAS,
	GRUPO_SAIU_FILABALC, GRUPO_SAIU_FILAMESAS,
	GRUPO_OCUPOU_BALCAO, GRUPO_OCUPOU_MESA,
	GRUPO_LIBEROU_BALCAO, GRUPO_LIBEROU_MESA, 
	GRUPO_TERMINA_COMER_EM, PEDIDO_PRONTO_TAKEAWAY, RESTAURANTE_FECHOU;
}
